"""YOUR COMPANY Shop QC. Digital execution of NC-QC-FAB-001 Rev 0."""

VERSION = "1.0.0"
APP_NAME = "YOUR COMPANY Shop QC"
COMPANY = "YOUR COMPANY, LLC"
COMPANY_ADDRESS = "[COMPANY ADDRESS]"
COMPANY_PHONE = "[COMPANY PHONE]"
