"""Full-building 3D assembler.

Composes a rectangular steel-framed building from primary members
(columns, eave beams, roof beams) into a single binary STL file.

Output is the assembled building geometry suitable for visualization
in any STL viewer. Member sections are looked up from the AISC database
loaded by stl_generator/aisc_lookup.

Design intent (v6.1.4):
    - Single-story rectangular building
    - Columns at every bay grid intersection
    - Perimeter eave beams (full ring)
    - Interior roof beams along the SHORT span (typical girder direction)
    - Optional X-bracing in end bays (defaults off)

All units are FEET internally, converted to inches at the STL boundary
to match the single-member STL files generated by stl_generator.
"""


import os
import struct
from typing import List, Tuple, Optional, Dict, Any

from . import stl_generator
from .stl_generator import (
    _write_stl_triangle,
    _i_beam_cross_section,
    _hss_cross_section,
    _triangulate_polygon,
    _extrude_edge,
)

# ─── Section property lookups ─────────────────────────────────────
# stl_generator.AISC_W_SHAPES   keyed "W14x82" → (d, bf, tf, tw, wt_lb_per_ft)
# stl_generator.AISC_HSS_SHAPES keyed "HSS10x10x1/2" → (w, h, t, wt_lb_per_ft)


def _normalize_shape_key(shape: str) -> str:
    """Normalize "W14X82" → "W14x82", "HSS10X10X1/2" → "HSS10x10x1/2"."""
    s = shape.strip().replace("×", "x").replace(" ", "")
    if not s:
        return s
    if s[0:1].isalpha():
        # Uppercase the leading letter(s): W or HSS prefix
        if s[:3].upper() == "HSS":
            s = "HSS" + s[3:]
        else:
            s = s[0].upper() + s[1:]
    s = s.replace("X", "x")
    return s


def _get_w_props(shape: str) -> Optional[Tuple[float, float, float, float, float]]:
    """Return (d, bf, tf, tw, wt_lb_per_ft) for a W shape, or None."""
    key = _normalize_shape_key(shape)
    if not key.startswith("W"):
        return None
    return stl_generator.AISC_W_SHAPES.get(key)


def _get_hss_props(shape: str) -> Optional[Tuple[float, float, float, float]]:
    """Return (w, h, t, wt_lb_per_ft) for an HSS shape, or None."""
    key = _normalize_shape_key(shape)
    if not key.startswith("HSS"):
        return None
    return stl_generator.AISC_HSS_SHAPES.get(key)


def _weight_per_ft(shape: str) -> float:
    """Look up weight lb/ft from either W or HSS table; return 0 if unknown."""
    w = _get_w_props(shape)
    if w is not None:
        return w[4]
    h = _get_hss_props(shape)
    if h is not None:
        return h[3]
    return 0.0


# ─── Member emitters (write triangles to open file) ───────────────
def _emit_column(f, shape: str,
                 x_ft: float, y_ft: float, height_ft: float) -> int:
    """Emit a vertical column from (x,y,0) to (x,y,height).

    Returns triangle count written.
    """
    x_in = x_ft * 12.0
    y_in = y_ft * 12.0
    z0 = 0.0
    z1 = height_ft * 12.0

    w = _get_w_props(shape)
    if w is not None:
        d, bf, tf, tw, _wt = w
        cross = _i_beam_cross_section(d, bf, tf, tw)
    else:
        h = _get_hss_props(shape)
        if h is None:
            return 0
        ww, hh, t, _wt = h
        outer, _inner = _hss_cross_section(ww, hh, t)
        cross = outer  # Skip hollow interior for assembled view (saves triangles)

    # Translate cross-section so it's centered at (x_in, y_in)
    cross_xy = [(x + x_in, y + y_in) for (x, y) in cross]

    tri_count = 0
    # Top cap
    for tri in _triangulate_polygon(cross_xy, z1):
        _write_stl_triangle(f, *tri, normal=(0, 0, 1))
        tri_count += 1
    # Bottom cap (reversed winding for outward normal)
    for tri in _triangulate_polygon(cross_xy, z0):
        v1, v2, v3 = tri
        _write_stl_triangle(f, v1, v3, v2, normal=(0, 0, -1))
        tri_count += 1
    # Side faces (extrude each edge)
    n = len(cross_xy)
    for i in range(n):
        p1 = cross_xy[i]
        p2 = cross_xy[(i + 1) % n]
        for tri in _extrude_edge(p1, p2, z0, z1):
            _write_stl_triangle(f, *tri)
            tri_count += 1
    return tri_count


def _emit_beam_general(f, shape: str,
                       x0_ft: float, y0_ft: float, z0_ft: float,
                       x1_ft: float, y1_ft: float, z1_ft: float) -> int:
    """Emit a beam from (x0,y0,z0) to (x1,y1,z1) in any direction.

    Cross-section orientation rule:
      - Length axis: along the beam.
      - Lateral 'u' axis: horizontal, perpendicular to the beam's horizontal
        projection. (For a horizontal beam, u is perpendicular to the beam.)
      - Vertical 'v' axis: perpendicular to both length and u, kept upward.
    This rotates the cross-section so the web stays vertical for horizontal
    beams and tilts naturally for sloped rafters.

    For purely vertical members (columns), fall back to _emit_column instead.
    """
    import math

    x0 = x0_ft * 12.0
    y0 = y0_ft * 12.0
    z0 = z0_ft * 12.0
    x1 = x1_ft * 12.0
    y1 = y1_ft * 12.0
    z1 = z1_ft * 12.0

    dx = x1 - x0
    dy = y1 - y0
    dz = z1 - z0
    length = math.sqrt(dx * dx + dy * dy + dz * dz)
    if length < 1e-6:
        return 0

    # Axis along length
    ax = (dx / length, dy / length, dz / length)
    # u axis: horizontal lateral
    horiz_len = math.sqrt(dx * dx + dy * dy)
    if horiz_len < 1e-6:
        # Purely vertical - should be a column; use X as lateral
        u = (1.0, 0.0, 0.0)
    else:
        u = (-dy / horiz_len, dx / horiz_len, 0.0)
    # v = ax × u (right-handed)
    v = (
        ax[1] * u[2] - ax[2] * u[1],
        ax[2] * u[0] - ax[0] * u[2],
        ax[0] * u[1] - ax[1] * u[0],
    )
    v_mag = math.sqrt(v[0] ** 2 + v[1] ** 2 + v[2] ** 2)
    if v_mag < 1e-6:
        return 0
    v = (v[0] / v_mag, v[1] / v_mag, v[2] / v_mag)
    # Make sure v points up
    if v[2] < 0:
        v = (-v[0], -v[1], -v[2])
        u = (-u[0], -u[1], -u[2])

    # Cross-section
    w = _get_w_props(shape)
    if w is not None:
        d, bf, tf, tw, _wt = w
        cross_2d = _i_beam_cross_section(d, bf, tf, tw)
    else:
        h = _get_hss_props(shape)
        if h is None:
            return 0
        ww, hh, t, _wt = h
        outer, _inner = _hss_cross_section(ww, hh, t)
        cross_2d = outer

    # Map (cu, cv) cross-section coords → 3D at start (end=0) or end (end=1)
    def map_point(cu, cv, end):
        base = (x0, y0, z0) if end == 0 else (x1, y1, z1)
        return (
            base[0] + cu * u[0] + cv * v[0],
            base[1] + cu * u[1] + cv * v[1],
            base[2] + cu * u[2] + cv * v[2],
        )

    tri_count = 0
    start_pts = [map_point(cu, cv, 0) for (cu, cv) in cross_2d]
    n = len(start_pts)
    # Start cap
    for i in range(1, n - 1):
        _write_stl_triangle(f, start_pts[0], start_pts[i], start_pts[i + 1],
                            normal=(-ax[0], -ax[1], -ax[2]))
        tri_count += 1
    end_pts = [map_point(cu, cv, 1) for (cu, cv) in cross_2d]
    # End cap (reversed winding)
    for i in range(1, n - 1):
        _write_stl_triangle(f, end_pts[0], end_pts[i + 1], end_pts[i],
                            normal=(ax[0], ax[1], ax[2]))
        tri_count += 1
    # Side faces
    for i in range(n):
        a = start_pts[i]
        b = start_pts[(i + 1) % n]
        c = end_pts[(i + 1) % n]
        d_pt = end_pts[i]
        _write_stl_triangle(f, a, b, c)
        _write_stl_triangle(f, a, c, d_pt)
        tri_count += 2
    return tri_count


# Back-compat alias for any caller still using the old name
def _emit_horizontal_beam(f, shape, x0_ft, y0_ft, x1_ft, y1_ft, z_ft):
    """Deprecated. Use _emit_beam_general. Kept for callers that pass flat beams."""
    return _emit_beam_general(f, shape, x0_ft, y0_ft, z_ft, x1_ft, y1_ft, z_ft)


# ─── Building plan and assembler ──────────────────────────────────
def plan_building(
    bays_x: int,
    bays_y: int,
    bay_spacing_x_ft: float = 25.0,
    bay_spacing_y_ft: float = 25.0,
    eave_height_ft: float = 18.0,
    column_size: str = 'W12X65',
    perimeter_beam_size: str = 'W21X44',
    interior_beam_size: str = 'W18X40',
    roof_type: str = 'flat',      # 'flat' or 'gable'
    roof_pitch: float = 0.25,     # rise/run; 0.25 = 3:12 pitch
    rafter_size: str = 'W18X35',
    ridge_size: str = 'W21X44',
    bracing: bool = False,        # X-bracing in end bays
    brace_size: str = 'HSS6x6x1/2',
) -> Dict[str, Any]:
    """Plan the member list for a rectangular building.

    Beams are stored as 8-tuples: (x0, y0, z0, x1, y1, z1, shape, role)
    where role ∈ {'perim', 'interior', 'ridge', 'rafter', 'brace'}.

    Returns dict with:
        columns: list of (x_ft, y_ft, height_ft, shape)
        beams:   list of (x0, y0, z0, x1, y1, z1, shape, role)
        total_members: int
        building_sf: float
        approx_tonnage: float
    """
    if bays_x < 1 or bays_y < 1:
        return {'error': 'bays_x and bays_y must be ≥ 1'}
    if roof_type not in ('flat', 'gable'):
        return {'error': f"roof_type must be 'flat' or 'gable', got '{roof_type}'"}

    columns = []
    beams = []

    n_col_x = bays_x + 1
    n_col_y = bays_y + 1
    eave = eave_height_ft
    x_max = bays_x * bay_spacing_x_ft
    y_max = bays_y * bay_spacing_y_ft

    # Columns at every grid intersection
    for i in range(n_col_x):
        for j in range(n_col_y):
            x = i * bay_spacing_x_ft
            y = j * bay_spacing_y_ft
            columns.append((x, y, eave, column_size))

    # Perimeter eave beams (full ring of the rectangle), at z=eave (flat for both roof types)
    for i in range(bays_x):
        x0 = i * bay_spacing_x_ft
        x1 = (i + 1) * bay_spacing_x_ft
        beams.append((x0, y_max, eave, x1, y_max, eave, perimeter_beam_size, 'perim'))
        beams.append((x0, 0.0, eave, x1, 0.0, eave, perimeter_beam_size, 'perim'))
    for j in range(bays_y):
        y0 = j * bay_spacing_y_ft
        y1 = (j + 1) * bay_spacing_y_ft
        beams.append((0.0, y0, eave, 0.0, y1, eave, perimeter_beam_size, 'perim'))
        beams.append((x_max, y0, eave, x_max, y1, eave, perimeter_beam_size, 'perim'))

    if roof_type == 'flat':
        # Interior beams: along Y direction at each interior X line (typical girder direction)
        for i in range(1, bays_x):
            x = i * bay_spacing_x_ft
            for j in range(bays_y):
                y0 = j * bay_spacing_y_ft
                y1 = (j + 1) * bay_spacing_y_ft
                beams.append((x, y0, eave, x, y1, eave, interior_beam_size, 'interior'))

    elif roof_type == 'gable':
        # Ridge along the LONGER axis. Frames span the SHORTER axis.
        if x_max >= y_max:
            # Ridge runs along X at y = y_max/2
            ridge_y = y_max / 2.0
            ridge_z = eave + (y_max / 2.0) * roof_pitch
            # Ridge beam (one continuous segment from x=0 to x=x_max at ridge_z)
            # Split into segments matching bay_spacing for cleaner topology
            for i in range(bays_x):
                xa = i * bay_spacing_x_ft
                xb = (i + 1) * bay_spacing_x_ft
                beams.append((xa, ridge_y, ridge_z, xb, ridge_y, ridge_z, ridge_size, 'ridge'))
            # Rafters at each frame line (every X column line)
            for i in range(n_col_x):
                x = i * bay_spacing_x_ft
                # Left rafter: from (x, 0, eave) to (x, ridge_y, ridge_z)
                beams.append((x, 0.0, eave, x, ridge_y, ridge_z, rafter_size, 'rafter'))
                # Right rafter: from (x, y_max, eave) to (x, ridge_y, ridge_z)
                beams.append((x, y_max, eave, x, ridge_y, ridge_z, rafter_size, 'rafter'))
        else:
            # Ridge runs along Y at x = x_max/2
            ridge_x = x_max / 2.0
            ridge_z = eave + (x_max / 2.0) * roof_pitch
            for j in range(bays_y):
                ya = j * bay_spacing_y_ft
                yb = (j + 1) * bay_spacing_y_ft
                beams.append((ridge_x, ya, ridge_z, ridge_x, yb, ridge_z, ridge_size, 'ridge'))
            for j in range(n_col_y):
                y = j * bay_spacing_y_ft
                beams.append((0.0, y, eave, ridge_x, y, ridge_z, rafter_size, 'rafter'))
                beams.append((x_max, y, eave, ridge_x, y, ridge_z, rafter_size, 'rafter'))

    # Optional X-bracing in the two end bays of the long direction (lateral stability)
    if bracing and bays_x >= 2 and bays_y >= 1:
        # Place bracing on the two short-side walls (y=0 and y=y_max), in the corner bays
        for y_wall in (0.0, y_max):
            # First bay (x=0 to x=bay_spacing_x)
            x0_b = 0.0
            x1_b = bay_spacing_x_ft
            beams.append((x0_b, y_wall, 0.0, x1_b, y_wall, eave, brace_size, 'brace'))
            beams.append((x1_b, y_wall, 0.0, x0_b, y_wall, eave, brace_size, 'brace'))
            # Last bay
            x0_b = (bays_x - 1) * bay_spacing_x_ft
            x1_b = bays_x * bay_spacing_x_ft
            beams.append((x0_b, y_wall, 0.0, x1_b, y_wall, eave, brace_size, 'brace'))
            beams.append((x1_b, y_wall, 0.0, x0_b, y_wall, eave, brace_size, 'brace'))

    # Building SF (footprint)
    building_sf = x_max * y_max

    # Approx tonnage (sum lengths × weight/ft)
    import math
    tonnage_lb = 0.0
    for (_, _, h, sh) in columns:
        tonnage_lb += h * _weight_per_ft(sh)
    for (x0, y0, z0, x1, y1, z1, sh, _role) in beams:
        L = math.sqrt((x1 - x0) ** 2 + (y1 - y0) ** 2 + (z1 - z0) ** 2)
        tonnage_lb += L * _weight_per_ft(sh)
    tonnage_tons = tonnage_lb / 2000.0

    return {
        'columns': columns,
        'beams': beams,
        'total_members': len(columns) + len(beams),
        'building_sf': building_sf,
        'approx_tonnage': round(tonnage_tons, 2),
        'bays_x': bays_x,
        'bays_y': bays_y,
        'eave_height_ft': eave_height_ft,
        'bay_spacing_x_ft': bay_spacing_x_ft,
        'bay_spacing_y_ft': bay_spacing_y_ft,
        'roof_type': roof_type,
        'roof_pitch': roof_pitch if roof_type == 'gable' else 0.0,
        'bracing': bracing,
    }


def build_full_building(
    bays_x: int,
    bays_y: int,
    output_path: str,
    bay_spacing_x_ft: float = 25.0,
    bay_spacing_y_ft: float = 25.0,
    eave_height_ft: float = 18.0,
    column_size: str = 'W12X65',
    perimeter_beam_size: str = 'W21X44',
    interior_beam_size: str = 'W18X40',
    roof_type: str = 'flat',
    roof_pitch: float = 0.25,
    rafter_size: str = 'W18X35',
    ridge_size: str = 'W21X44',
    bracing: bool = False,
    brace_size: str = 'HSS6x6x1/2',
) -> Dict[str, Any]:
    """Assemble a full rectangular building into one binary STL.

    Returns dict with path, triangle_count, member_count, file_size_bytes,
    plus the plan summary.
    """
    plan = plan_building(
        bays_x, bays_y,
        bay_spacing_x_ft=bay_spacing_x_ft,
        bay_spacing_y_ft=bay_spacing_y_ft,
        eave_height_ft=eave_height_ft,
        column_size=column_size,
        perimeter_beam_size=perimeter_beam_size,
        interior_beam_size=interior_beam_size,
        roof_type=roof_type,
        roof_pitch=roof_pitch,
        rafter_size=rafter_size,
        ridge_size=ridge_size,
        bracing=bracing,
        brace_size=brace_size,
    )
    if 'error' in plan:
        return plan

    # Validate every distinct shape resolves
    shapes_to_check = {column_size, perimeter_beam_size, interior_beam_size}
    if roof_type == 'gable':
        shapes_to_check.update({rafter_size, ridge_size})
    if bracing:
        shapes_to_check.add(brace_size)
    for sh in shapes_to_check:
        if _get_w_props(sh) is None and _get_hss_props(sh) is None:
            return {'error': f"shape '{sh}' not in AISC database"}

    # Write binary STL
    os.makedirs(os.path.dirname(os.path.abspath(output_path)) or '.', exist_ok=True)
    with open(output_path, 'wb') as f:
        f.write(b'\0' * 80)
        f.write(struct.pack('<I', 0))  # placeholder

        tri_count = 0
        for (x, y, h, shape) in plan['columns']:
            tri_count += _emit_column(f, shape, x, y, h)
        for (x0, y0, z0, x1, y1, z1, shape, _role) in plan['beams']:
            tri_count += _emit_beam_general(f, shape, x0, y0, z0, x1, y1, z1)

        f.seek(80)
        f.write(struct.pack('<I', tri_count))

    size = os.path.getsize(output_path)
    return {
        'ok': True,
        'path': output_path,
        'triangle_count': tri_count,
        'member_count': plan['total_members'],
        'file_size_bytes': size,
        'plan': {k: v for k, v in plan.items() if k not in ('columns', 'beams')},
    }
