-- YOUR COMPANY Shop QC - Supabase Postgres schema (system of record)
--
-- Everything lives under a dedicated schema named shopqc, never public, so ShopQC
-- stays isolated whether it lands in its own Supabase project or shares an existing
-- database. Apply this in the Supabase SQL editor (a Joseph/Owner task; see
-- SUPABASE_SETUP.md), then apply rls.sql to create the limited app role.
--
-- This mirrors the eight SQLite tables in shopqc/db.py one to one. Deliberate type
-- choices so the app's data contract round-trips with no per-value translation:
--   - id columns use IDENTITY (GENERATED BY DEFAULT so the sync can also supply ids)
--   - boolean flags and counts stay INTEGER (the app reads and writes 0 and 1)
--   - dates stay TEXT holding the app's "YYYY-MM-DD HH:MM:SS" and ISO strings
--     (the app treats them as opaque strings; TEXT avoids a timestamp cast on read)
--   - updated_at is also TEXT: a UTC millisecond string the offline sync compares
--     lexically for last-write-wins, matching the cache clock exactly
--   - Fy, Fu, CE and tonnage are DOUBLE PRECISION (SQLite REAL)
-- Two columns are added to every table for the offline sync, and are invisible to
-- the app: sync_uid (a stable cross-store identity) and updated_at (last-write-wins
-- clock). The fastener_lots table is added in Phase B alongside the bolt receiving
-- feature; the audit_log below records every change the offline sync applies.

CREATE SCHEMA IF NOT EXISTS shopqc;

-- gen_random_uuid() is built into Postgres 13+ (Supabase is newer), so no extension
-- is required. If running on an older server, enable pgcrypto first.

-- ---------------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.projects (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            text NOT NULL UNIQUE,
  job_number      text NOT NULL,
  name            text NOT NULL,
  gc_name         text,
  contract_number text,
  tonnage         double precision DEFAULT 0,
  ias_required    integer DEFAULT 0,
  created_date    text NOT NULL,
  status          text NOT NULL DEFAULT 'ACTIVE',
  sync_uid        uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at      text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS')
);

-- ---------------------------------------------------------------------------
-- bol_items
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.bol_items (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id        integer NOT NULL REFERENCES shopqc.projects(id),
  line_number       integer,
  section           text NOT NULL,
  quantity_ordered  integer NOT NULL DEFAULT 0,
  quantity_received integer NOT NULL DEFAULT 0,
  heat_number       text,
  lot_number        text,
  astm_grade        text,
  fy                double precision,
  fu                double precision,
  ce                double precision,
  mtr_verified      integer DEFAULT 0,
  received_date     text,
  sync_uid          uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at        text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS')
);

-- ---------------------------------------------------------------------------
-- pieces
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.pieces (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    integer NOT NULL REFERENCES shopqc.projects(id),
  piece_id      text NOT NULL UNIQUE,
  section       text NOT NULL,
  heat_number   text,
  lot_number    text,
  status        text NOT NULL DEFAULT 'RECEIVED',
  label_printed integer DEFAULT 0,
  traveler_type text NOT NULL DEFAULT 'STRUCTURAL',
  created_date  text NOT NULL,
  sync_uid      uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at    text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS')
);

-- ---------------------------------------------------------------------------
-- traveler_fields
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.traveler_fields (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  piece_pk     integer NOT NULL REFERENCES shopqc.pieces(id),
  field_number integer NOT NULL,
  field_name   text NOT NULL,
  value        text,
  signed_by    text,
  timestamp    text,
  notes        text,
  sync_uid     uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at   text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS'),
  UNIQUE (piece_pk, field_number)
);

-- ---------------------------------------------------------------------------
-- ncrs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.ncrs (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id            integer NOT NULL REFERENCES shopqc.projects(id),
  piece_pk              integer REFERENCES shopqc.pieces(id),
  gate                  integer NOT NULL,
  category              text NOT NULL,
  description           text NOT NULL,
  opened_by             text NOT NULL,
  opened_date           text NOT NULL,
  disposition           text,
  disposition_authority text,
  eor_reference         text,
  closed_by             text,
  closed_date           text,
  status                text NOT NULL DEFAULT 'OPEN',
  sync_uid              uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at            text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS')
);

-- ---------------------------------------------------------------------------
-- rir_records
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.rir_records (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id      integer NOT NULL REFERENCES shopqc.projects(id),
  lot_number      text,
  signed_by       text NOT NULL,
  signed_date     text NOT NULL,
  all_checks_json text NOT NULL,
  sync_uid        uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at      text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS')
);

-- ---------------------------------------------------------------------------
-- weld_records
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.weld_records (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  piece_pk       integer NOT NULL REFERENCES shopqc.pieces(id),
  weld_type      text,
  wps_file       text,
  welder_id      text,
  pre_weld_by    text,
  pre_weld_date  text,
  vt_result      text,
  vt_by          text,
  vt_date        text,
  ndt_type       text,
  ndt_result     text,
  ndt_report_ref text,
  sync_uid       uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at     text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS')
);

-- ---------------------------------------------------------------------------
-- release_records
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.release_records (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  piece_pk            integer NOT NULL REFERENCES shopqc.pieces(id),
  shop_director_sign  text NOT NULL,
  cwi_sign            text NOT NULL,
  ceo_sign            text,
  release_date        text NOT NULL,
  truck_load_ref      text,
  certificate_printed integer DEFAULT 0,
  sync_uid            uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at          text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS')
);

-- ---------------------------------------------------------------------------
-- fastener_lots (Phase B): high-strength bolt receiving (RCSC / ASTM F3125).
-- Acceptance is enforced in the app (db.fastener_receiving_blocked_reason); this
-- table records the lot, the ROCAP test lot number, and the marking, cert,
-- galvanized, and lube checks. Flags stay INTEGER (0/1) like the app contract.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.fastener_lots (
  id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id             integer NOT NULL REFERENCES shopqc.projects(id),
  assembly_type          text NOT NULL,
  quantity               integer NOT NULL DEFAULT 0,
  rocap_lot_no           text,
  markings_verified      integer DEFAULT 0,
  mfr_cert_on_file       integer DEFAULT 0,
  galvanized             integer DEFAULT 0,
  lube_check_done        integer DEFAULT 0,
  rocap_result_reference text,
  received_complete      integer DEFAULT 0,
  received_date          text,
  created_date           text NOT NULL,
  sync_uid               uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  updated_at             text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS')
);
CREATE INDEX IF NOT EXISTS idx_fastener_project ON shopqc.fastener_lots(project_id);

-- ---------------------------------------------------------------------------
-- audit_log: one append-only row per change the offline sync applies to this
-- database, so a reconnect that merges queued floor scans is fully traceable.
-- payload is the applied row as a JSON string (TEXT keeps the sync SQL identical
-- across Postgres and the test harness; query it with payload::jsonb when needed).
-- outcome is 'applied' or 'superseded' (last-write-wins kept the existing row).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shopqc.audit_log (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name  text NOT NULL,
  sync_uid    uuid NOT NULL,
  op          text NOT NULL,
  payload     text,
  source      text,
  station     text,
  applied_at  text NOT NULL,
  outcome     text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pieces_project ON shopqc.pieces(project_id);
CREATE INDEX IF NOT EXISTS idx_traveler_piece ON shopqc.traveler_fields(piece_pk);
CREATE INDEX IF NOT EXISTS idx_ncrs_project ON shopqc.ncrs(project_id);
CREATE INDEX IF NOT EXISTS idx_ncrs_status ON shopqc.ncrs(status);
CREATE INDEX IF NOT EXISTS idx_audit_table_uid ON shopqc.audit_log(table_name, sync_uid);

-- ---------------------------------------------------------------------------
-- updated_at maintenance. Online edits stamp updated_at with a fresh UTC
-- millisecond string so last-write-wins compares against a current clock. The
-- offline sync supplies the original local change time instead, so it sets
-- shopqc.sync_apply = 'on' for its connection and this trigger then leaves the
-- provided updated_at untouched.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION shopqc.touch_updated_at() RETURNS trigger AS $$
BEGIN
  IF current_setting('shopqc.sync_apply', true) IS DISTINCT FROM 'on' THEN
    NEW.updated_at := to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS.MS');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['projects','bol_items','pieces','traveler_fields',
                           'ncrs','rir_records','weld_records','release_records',
                           'fastener_lots'] LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS touch_%1$s ON shopqc.%1$s;', t);
    EXECUTE format(
      'CREATE TRIGGER touch_%1$s BEFORE INSERT OR UPDATE ON shopqc.%1$s '
      'FOR EACH ROW EXECUTE FUNCTION shopqc.touch_updated_at();', t);
  END LOOP;
END $$;
